/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

/**
 *
 * @author Arell
 */
public class Pagina_Datos_Finales_Consulta extends javax.swing.JFrame {

    /**
     * Creates new form Pagina_Datos_Finales_Consulta
     */
    public Pagina_Datos_Finales_Consulta() {
        initComponents();
        this.setTitle("Pagina de Datos Finales acerca la Consulta");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPanel5 = new javax.swing.JPanel();
        FondoAzul5 = new javax.swing.JPanel();
        Hospital_General5 = new javax.swing.JLabel();
        btnAgendar = new javax.swing.JButton();
        FechaYHora = new javax.swing.JLabel();
        DatosFinalesConsulta = new javax.swing.JLabel();
        Medico = new javax.swing.JLabel();
        Especialista = new javax.swing.JLabel();
        CampoEspecialista = new javax.swing.JTextField();
        CampoMedico = new javax.swing.JTextField();
        CampoFechaYHora = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FondoPanel5.setBackground(new java.awt.Color(255, 255, 255));
        FondoPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FondoPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoAzul5.setBackground(new java.awt.Color(0, 153, 255));
        FondoAzul5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Hospital_General5.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        Hospital_General5.setText("Hospital General");

        javax.swing.GroupLayout FondoAzul5Layout = new javax.swing.GroupLayout(FondoAzul5);
        FondoAzul5.setLayout(FondoAzul5Layout);
        FondoAzul5Layout.setHorizontalGroup(
            FondoAzul5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoAzul5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Hospital_General5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(526, Short.MAX_VALUE))
        );
        FondoAzul5Layout.setVerticalGroup(
            FondoAzul5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoAzul5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Hospital_General5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        FondoPanel5.add(FondoAzul5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 40));

        btnAgendar.setBackground(new java.awt.Color(0, 0, 0));
        btnAgendar.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        btnAgendar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgendar.setText("Agendar");
        btnAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarActionPerformed(evt);
            }
        });
        FondoPanel5.add(btnAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 130, 30));

        FechaYHora.setFont(new java.awt.Font("Roboto", 3, 24)); // NOI18N
        FechaYHora.setText("Fecha y Hora");
        FondoPanel5.add(FechaYHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 140, -1));

        DatosFinalesConsulta.setFont(new java.awt.Font("Roboto", 3, 24)); // NOI18N
        DatosFinalesConsulta.setText("Datos Finales de la Consulta");
        FondoPanel5.add(DatosFinalesConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 330, -1));

        Medico.setFont(new java.awt.Font("Roboto", 3, 24)); // NOI18N
        Medico.setText("Medico");
        FondoPanel5.add(Medico, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 90, -1));

        Especialista.setFont(new java.awt.Font("Roboto", 3, 24)); // NOI18N
        Especialista.setText("Especialista");
        FondoPanel5.add(Especialista, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 140, -1));

        CampoEspecialista.setText("Cardiologo");
        CampoEspecialista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoEspecialistaActionPerformed(evt);
            }
        });
        FondoPanel5.add(CampoEspecialista, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 200, 30));

        CampoMedico.setText("Perez Juan");
        CampoMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoMedicoActionPerformed(evt);
            }
        });
        FondoPanel5.add(CampoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 200, 30));

        CampoFechaYHora.setText("12/12/2024 - 2:30");
        FondoPanel5.add(CampoFechaYHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(FondoPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(FondoPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgendarActionPerformed

    private void CampoMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoMedicoActionPerformed

    private void CampoEspecialistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoEspecialistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoEspecialistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pagina_Datos_Finales_Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pagina_Datos_Finales_Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pagina_Datos_Finales_Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pagina_Datos_Finales_Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pagina_Datos_Finales_Consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoEspecialista;
    private javax.swing.JTextField CampoFechaYHora;
    private javax.swing.JTextField CampoMedico;
    private javax.swing.JLabel DatosFinalesConsulta;
    private javax.swing.JLabel Especialista;
    private javax.swing.JLabel FechaYHora;
    private javax.swing.JPanel FondoAzul1;
    private javax.swing.JPanel FondoAzul2;
    private javax.swing.JPanel FondoAzul3;
    private javax.swing.JPanel FondoAzul4;
    private javax.swing.JPanel FondoAzul5;
    private javax.swing.JPanel FondoPanel1;
    private javax.swing.JPanel FondoPanel2;
    private javax.swing.JPanel FondoPanel3;
    private javax.swing.JPanel FondoPanel4;
    private javax.swing.JPanel FondoPanel5;
    private javax.swing.JLabel Hospital_General1;
    private javax.swing.JLabel Hospital_General2;
    private javax.swing.JLabel Hospital_General3;
    private javax.swing.JLabel Hospital_General4;
    private javax.swing.JLabel Hospital_General5;
    private javax.swing.JLabel Medico;
    private javax.swing.JButton btnAgendar;
    // End of variables declaration//GEN-END:variables
}
