package presentation;

import JPAEntities.DoctorEntity;
import JPAEntities.PatientEntity;
import JPAEntities.Specialization;
import appointment.system.AppointmentStatus;
import appointment.system.IAppointmentManager;
import appointment.system.NewAppointmentDTO;
import doctor.system.ExistentDoctorDTO;
import doctor.system.IDoctorDAO;
import factory.Factory;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import patient.system.ExistentPatientDTO;
import com.toedter.calendar.JDateChooser;
import patient.system.IPatientDAO;

public class JFrameRegisterAppointment extends javax.swing.JFrame {

    private ExistentPatientDTO paciente;
    private ExistentDoctorDTO doctorP1;
    private List<ExistentDoctorDTO> doctores;
    private ExistentDoctorDTO existentDoctorDTO;
    private ExistentPatientDTO existentPateintDTO;
    private JDateChooser dateChooser;
    private List<Calendar> limitDays;

    public JFrameRegisterAppointment(NewAppointmentDTO appointmentDTO, ExistentDoctorDTO doctorDTO) {

        this.doctorP1 = doctorDTO;
        initComponents();
        dateChooser();
        limitarFecha();
        txtNota.setText(appointmentDTO.getNote());
        cmbDoctor.setSelectedItem(appointmentDTO.getPatient());
        dateChooser.setCalendar(appointmentDTO.getAppointmentDate());

    }

    public JFrameRegisterAppointment(NewAppointmentDTO appointmentDTO, ExistentPatientDTO patientDTO) {
        this.paciente = patientDTO;
        initComponents();
        dateChooser();
        limitarFecha();
        txtNota.setText(appointmentDTO.getNote());
        cbxSpecialization.setSelectedItem(appointmentDTO.getDoctor().getSpecialization());
        cmbDoctor.setSelectedItem(appointmentDTO.getDoctor());
        dateChooser.setCalendar(appointmentDTO.getAppointmentDate());

    }

    public JFrameRegisterAppointment(ExistentPatientDTO paciente) {
        this.paciente = paciente;
        initComponents();
        dateChooser();
        limitarFecha();
        limitDays = new ArrayList<>();
    }

    public JFrameRegisterAppointment(ExistentDoctorDTO doctor) {
        this.doctorP1 = doctor;
        initComponents();
        dateChooser();
        limitarFecha();
        lblSpecilaization.setEnabled(false);
        cbxSpecialization.setEnabled(false);
        lblDoctors.setText("Patients");
        limitDays = new ArrayList<>();
        patientList();
    }

    public void patientList() {

        IPatientDAO patientDAO = Factory.getPatientDAO();
        List<ExistentPatientDTO> patientList = patientDAO.findAllPatient();
        cmbDoctor.removeAllItems();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        cmbDoctor.setModel(model);
        for (ExistentPatientDTO patient : patientList) {
            model.addElement(patient);
        }
        this.cmbDoctor.setVisible(true);

    }

    public void dateChooser() {

        dateChooser = new JDateChooser();
        dateChooser.setBounds(lblFecha.getBounds());
        this.add(dateChooser);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPanel = new javax.swing.JPanel();
        FondoAzul = new javax.swing.JPanel();
        Hospital_General = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cmbDoctor = new javax.swing.JComboBox<>();
        lblDoctors = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNota = new javax.swing.JTextField();
        cbxSpecialization = new javax.swing.JComboBox<>();
        lblSpecilaization = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoPanel.setBackground(new java.awt.Color(255, 255, 255));
        FondoPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoAzul.setBackground(new java.awt.Color(0, 153, 255));
        FondoAzul.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        FondoAzul.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Hospital_General.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Hospital_General.setText("General Hospital");
        FondoAzul.add(Hospital_General, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 39));

        FondoPanel.add(FondoAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Register Appointment");
        FondoPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        FondoPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, -1, -1));

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        FondoPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        cmbDoctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        cmbDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbDoctorMouseClicked(evt);
            }
        });
        cmbDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDoctorActionPerformed(evt);
            }
        });
        FondoPanel.add(cmbDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 110, -1));

        lblDoctors.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDoctors.setText("Doctors");
        FondoPanel.add(lblDoctors, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));
        FondoPanel.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setText("Date ");
        FondoPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setText("Note...");
        FondoPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));

        txtNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNotaActionPerformed(evt);
            }
        });
        FondoPanel.add(txtNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 320, 40));

        cbxSpecialization.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FAMILY",   "PEDIATRIC",
            "SURGERY",
            "PSYCHIATRY",
            "ANESTHIOLOGY",
            "CARDIOLGY"}));
cbxSpecialization.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        cbxSpecializationActionPerformed(evt);
    }
    });
    FondoPanel.add(cbxSpecialization, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 110, -1));

    lblSpecilaization.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    lblSpecilaization.setText("Specialization");
    FondoPanel.add(lblSpecilaization, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));
    FondoPanel.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 110, 20));

    getContentPane().add(FondoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 880, 490));

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        limitDays();
        List<Calendar> dias = limitDays;
        for (Calendar calendar : limitDays) {

            if (dateChooser.getCalendar().get(Calendar.MONTH) == calendar.get(Calendar.MONTH)) {

                if (dateChooser.getCalendar().get(Calendar.DAY_OF_MONTH) == calendar.get(Calendar.DAY_OF_MONTH)) {

                    if (dateChooser.getCalendar().get(Calendar.YEAR) == calendar.get(Calendar.YEAR)) {

                        JOptionPane.showMessageDialog(this, "This date has already been set aside");
                        return;
                    }
                }
            }
        }

        if (doctorP1 == null) {

            NewAppointmentDTO newAppointmentDTO = new NewAppointmentDTO();
            newAppointmentDTO.setDoctor(existentDoctorDTO);
            newAppointmentDTO.setPatient(paciente);
            newAppointmentDTO.setStatus(AppointmentStatus.ACTIVE);
            newAppointmentDTO.setAppointmentDate(dateChooser.getCalendar());
            newAppointmentDTO.setNote(txtNota.getText());

            JFrameConfirmAppointment confirm = new JFrameConfirmAppointment(newAppointmentDTO, paciente);
            confirm.setVisible(true);
            this.dispose();

        } else {

            NewAppointmentDTO newAppointmentDTO = new NewAppointmentDTO();
            newAppointmentDTO.setDoctor(doctorP1);
            newAppointmentDTO.setPatient(existentPateintDTO);
            newAppointmentDTO.setStatus(AppointmentStatus.ACTIVE);
            newAppointmentDTO.setAppointmentDate(dateChooser.getCalendar());
            newAppointmentDTO.setNote(txtNota.getText());

            JFrameConfirmAppointment confirm = new JFrameConfirmAppointment(newAppointmentDTO, doctorP1);
            confirm.setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (doctorP1 == null) {

            JFrameInitialPatient pat = new JFrameInitialPatient(paciente.getId());
            pat.setVisible(true);
            this.dispose();

        } else {

            JFrameInitialMedicos medic = new JFrameInitialMedicos(doctorP1.getId());
            medic.setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDoctorActionPerformed

        if (doctorP1 == null) {
            existentDoctorDTO = (ExistentDoctorDTO) cmbDoctor.getSelectedItem();
        } else {
            existentPateintDTO = (ExistentPatientDTO) cmbDoctor.getSelectedItem();
        }
    }//GEN-LAST:event_cmbDoctorActionPerformed

    private void cbxSpecializationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSpecializationActionPerformed

        if (doctorP1 == null) {
            Specialization specializationEnum = Specialization.PEDIATRIC;
            IDoctorDAO doctorDAO = Factory.getDoctorDAO();

            String selectedSpecialization = (String) cbxSpecialization.getSelectedItem();
            doctores = doctorDAO.searchBySpecialization(specializationEnum.StringToEnum(selectedSpecialization));
            cmbDoctor.removeAllItems();
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            cmbDoctor.setModel(model);
            for (ExistentDoctorDTO doctor : doctores) {
                model.addElement(doctor);
            }
            this.cmbDoctor.setVisible(true);
        }
    }//GEN-LAST:event_cbxSpecializationActionPerformed

    public void limitDays() {

        IAppointmentManager appointmentManager = Factory.getAppointmentManager();
        if (doctorP1 == null) {
            IDoctorDAO doctorDAO = Factory.getDoctorDAO();
            ExistentDoctorDTO existentDoctor = (ExistentDoctorDTO) cmbDoctor.getSelectedItem();
            DoctorEntity doctorEntity = doctorDAO.ExistentDtoToEntity(existentDoctor);
            if (appointmentManager.findLimitDays(doctorEntity) != null) {
                limitDays = appointmentManager.findLimitDays(doctorEntity);
            }
        } else {
            IPatientDAO patientDAO = Factory.getPatientDAO();
            ExistentPatientDTO existentPatientDTO = (ExistentPatientDTO) cmbDoctor.getSelectedItem();
            PatientEntity patientEntity = patientDAO.findPatient(existentPatientDTO.getId());
            if (appointmentManager.findLimitDays(patientEntity) != null) {
                limitDays = appointmentManager.findLimitDays(patientEntity);
            }
        }
    }

    private void cmbDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbDoctorMouseClicked
        // TODO add your handling code 
        if (doctorP1 == null) {
            if (cmbDoctor.getSize() != null) {
                limitDays();
            }
        }
    }//GEN-LAST:event_cmbDoctorMouseClicked

    private void txtNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNotaActionPerformed

    public void limitarFecha() {
        Calendar fechaMinima = Calendar.getInstance();
        fechaMinima.set(Calendar.DATE, 1);
        Date minimo = fechaMinima.getTime();

        Calendar fechaMaxima = Calendar.getInstance();
        fechaMaxima.add(Calendar.YEAR, 2);
        Date maximo = fechaMaxima.getTime();

        dateChooser.setSelectableDateRange(minimo, maximo);

    }

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JFrameConfirmAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JFrameConfirmAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JFrameConfirmAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JFrameConfirmAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JFrameConfirmAppointment().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoAzul;
    private javax.swing.JPanel FondoPanel;
    private javax.swing.JLabel Hospital_General;
    private javax.swing.JComboBox<String> cbxSpecialization;
    private javax.swing.JComboBox<String> cmbDoctor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblDoctors;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblSpecilaization;
    private javax.swing.JTextField txtNota;
    // End of variables declaration//GEN-END:variables
}
